name: Deploy on gh-pages
on:
  push:
    branches: ["main"]
jobs:
 run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Change directory to dist
      - run: cd dist
      - name: Git actions
      - run: git init && git checkout -B main && git add -A && git commit -m 'deploy'
      - name: Push to gh-pages branch
      - run: git push -f git@github.com:IgorAtilar/espeon.git main:gh-pages
